name: integration test all
on:
  push:
    # branches:
      # - master
  pull_request:
    branches:
      - master
jobs:
  integration:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest] # macos is not supported by GitHub actions

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - uses: satackey/action-docker-layer-caching@fix-#37-filename-too-long-release
        with:
          key: docker-${{ runner.os }}-${{ github.workflow }}-{hash}

      - name: integration
        run: docker build . -f test/integration/integration.dockerfile -t integration && docker run integration
